### ISSUE TITLE
Run SDK Wrong with buildozer android debug

### ISSUE THREAD

**Issue by javychen-cn** [javychen-cn/kivy-buildozer#1]
I'm learning Kivy and building an app on linux, but there was an error in running buildozer. How can I solve this problem? Please give me your advice. Thank you.

⚡ buildozer android debug deploy run
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /home/javy/.local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-12-openjdk/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-12-openjdk/bin/keytool
# Install platform
# Run 'git config --get remote.origin.url'
# Cwd /home/javy/.buildozer/android/platform/python-for-android
https://github.com/kivy/python-for-android.git
# Run 'git branch -vv'
# Cwd /home/javy/.buildozer/android/platform/python-for-android
* master dd69749f [origin/master] Merge pull request #1955 from kivy/release-2019.08.09
# Run '/usr/sbin/python -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517\' \'pytoml\' \'virtualenv\''
# Cwd None
# Apache ANT found at /usr/share/ant
# Android SDK found at /opt/android-sdk
# Android NDK found at /opt/android-ndk
# Recommended android's NDK version by p4a is: 17c
# Installing/updating SDK platform tools if necessary
# Run '/opt/android-sdk/tools/bin/sdkmanager tools platform-tools'
# Cwd /opt/android-sdk
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
# Command failed: /opt/android-sdk/tools/bin/sdkmanager tools platform-tools
# ENVIRONMENT:
#     ANDROID_HOME = '/opt/android-sdk'
#     ANDROID_NDK = '/opt/android-ndk'
#     ANDROID_NDK_HOME = '/opt/android-ndk'
#     COLORFGBG = '15;0'
#     COLORTERM = 'truecolor'
#     DBUS_SESSION_BUS_ADDRESS = 'unix:path=/run/user/1000/bus'
#     DESKTOP_SESSION = '/usr/share/xsessions/plasma'
#     DISPLAY = ':0'
#     GS_LIB = '/home/javy/.fonts'
#     GTK_MODULES = 'canberra-gtk-module'
#     HOME = '/home/javy'
#     KDE_FULL_SESSION = 'true'
#     KDE_SESSION_UID = '1000'
#     KDE_SESSION_VERSION = '5'
#     KONSOLE_DBUS_SERVICE = ':1.53'
#     KONSOLE_DBUS_SESSION = '/Sessions/1'
#     KONSOLE_DBUS_WINDOW = '/Windows/1'
#     KONSOLE_PROFILE_NAME = 'Shell'
#     KONSOLE_VERSION = '190800'
#     LANG = 'zh_CN.UTF-8'
#     LANGUAGE = ''
#     LC_ADDRESS = 'zh_CN.UTF-8'
#     LC_IDENTIFICATION = 'zh_CN.UTF-8'
#     LC_MEASUREMENT = 'zh_CN.UTF-8'
#     LC_MONETARY = 'zh_CN.UTF-8'
#     LC_NAME = 'zh_CN.UTF-8'
#     LC_NUMERIC = 'zh_CN.UTF-8'
#     LC_PAPER = 'zh_CN.UTF-8'
#     LC_TELEPHONE = 'zh_CN.UTF-8'
#     LC_TIME = 'zh_CN.UTF-8'
#     LOGNAME = 'javy'
#     MAIL = '/var/spool/mail/javy'
#     MOZ_PLUGIN_PATH = '/usr/lib/mozilla/plugins'
#     OLDPWD = '/home/javy'
#     PAM_KWALLET5_LOGIN = '/run/user/1000/kwallet5.socket'
#     PATH = '/usr/share/ant/bin:/home/javy/crystax-ndk-10.3.2:/home/javy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'                                       
#     PROFILEHOME = ''
#     PWD = '/home/javy'
#     QT_AUTO_SCREEN_SCALE_FACTOR = '0'
#     QT_LINUX_ACCESSIBILITY_ALWAYS_ON = '1'
#     SESSION_MANAGER = 'local/power-man:@/tmp/.ICE-unix/691,unix/power-man:/tmp/.ICE-unix/691'
#     SHELL = '/bin/zsh'
#     SHELL_SESSION_ID = 'e801c6d34d98406bba9aa5383a51126b'
#     SHLVL = '2'
#     TERM = 'xterm-256color'
#     USER = 'javy'
#     WINDOWID = '58720263'
#     XAUTHORITY = '/home/javy/.Xauthority'
#     XCURSOR_THEME = 'breeze_cursors'
#     XDG_CURRENT_DESKTOP = 'KDE'
#     XDG_DATA_DIRS = '/home/javy/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'                                                                                  
#     XDG_RUNTIME_DIR = '/run/user/1000'
#     XDG_SEAT = 'seat0'
#     XDG_SEAT_PATH = '/org/freedesktop/DisplayManager/Seat0'
#     XDG_SESSION_CLASS = 'user'
#     XDG_SESSION_DESKTOP = 'KDE'
#     XDG_SESSION_ID = '2'
#     XDG_SESSION_PATH = '/org/freedesktop/DisplayManager/Session1'
#     XDG_SESSION_TYPE = 'x11'
#     XDG_VTNR = '1'
#     XMODIFIERS = '@im=fcitx'
#     _ = '/home/javy/.local/bin/buildozer'
#     ZSH = '/home/javy/.oh-my-zsh'
#     PAGER = 'less'
#     LESS = '-R'
#     LSCOLORS = 'Gxfxcxdxbxegedabagacad'
#     LS_COLORS = 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

**Comment by javychen-cn** [comment]
unistall jdk12
install java8

fixed!
